name: Apidae
options:
  bundleIdPrefix: app.getapidae
  deploymentTarget:
    macOS: "14.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

schemes:
  Apidae:
    build:
      targets:
        Apidae: all
        ApidaeTests: [test]
    test:
      targets:
        - ApidaeTests

targets:
  Apidae:
    type: application
    platform: macOS
    sources:
      - path: Apidae
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.getapidae.mac
        PRODUCT_NAME: Apidae
        INFOPLIST_FILE: Apidae/Info.plist
        CODE_SIGN_ENTITLEMENTS: Apidae/Apidae.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  ApidaeTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ApidaeTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.getapidae.mac.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Apidae.app/Contents/MacOS/Apidae"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Apidae
